name: Setup Docker Compose

on:
  workflow_call:
    secrets:
      SSH_REMOTE_HOST:
        required: true
      SSH_REMOTE_USER:
        required: true
      SSH_PRIVATE_KEY:
        required: true

jobs:
  setup-docker-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker and Docker Compose
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_REMOTE_HOST }}
          username: ${{ secrets.SSH_REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Install Docker if not installed
            if ! command -v docker &> /dev/null; then
              echo "Docker not found. Installing..."
              sudo apt update
              sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
              sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
              sudo apt update
              sudo apt install -y docker-ce
            else
              echo "Docker is already installed."
            fi

            # Install Docker Compose if not installed
            if ! command -v docker-compose &> /dev/null; then
              echo "Docker Compose not found. Installing..."
              DOCKER_COMPOSE_VERSION=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)
              sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            else
              echo "Docker Compose is already installed."
            fi

            # Verify installations
            echo "Docker version:"
            docker --version
            echo "Docker Compose version:"
            docker-compose --version

      - name: Test Docker and Docker Compose
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_REMOTE_HOST }}
          username: ${{ secrets.SSH_REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Testing Docker..."
            sudo docker run hello-world

            echo "Testing Docker Compose..."
            mkdir -p ~/docker-test
            echo "version: '3'\nservices:\n  web:\n    image: nginx" > ~/docker-test/docker-compose.yml
            cd ~/docker-test
            sudo docker-compose up -d
            sleep 5
            curl -I http://localhost:80
            sudo docker-compose down
            rm -rf ~/docker-test
