name: Setup Cloudflare Domain

on:
  workflow_call:
    secrets:
      DOMAIN_NAME:
        description: 'Subdomain to add (e.g. test)'
        required: true
      SERVER_IP:
        description: 'Content for DNS record (IP or hostname)'
        required: true
      CLOUDFLARE_API_TOKEN:
        required: true
      CLOUDFLARE_ZONE_ID:
        required: true
    inputs:
      record_type:
        description: 'DNS record type (A, CNAME, etc.)'
        default: 'A'
        type: string
        required: false
      record_ttl:
        description: 'TTL for the DNS record'
        default: 3600
        type: number
        required: false

jobs:
  setup-ssl:
    runs-on: ubuntu-latest
    steps:
      - name: Add subdomain DNS record
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          SUBDOMAIN: ${{ secrets.DOMAIN_NAME }}
          RECORD_TYPE: ${{ inputs.record_type }}
          RECORD_CONTENT: ${{ secrets.SERVER_IP }}
          TTL: ${{ inputs.record_ttl }}
        run: |
          echo "Adding DNS record for subdomain: $SUBDOMAIN"

          RESPONSE=$(curl -s -X POST "https://api.cloudflare.com/client/v4/zones/${CLOUDFLARE_ZONE_ID}/dns_records" \
            -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
            -H "Content-Type: application/json" \
            --data '{
              "type": "'"${RECORD_TYPE}"'",
              "name": "'"${SUBDOMAIN}"'",
              "content": "'"${RECORD_CONTENT}"'",
              "ttl": '"${TTL}"',
              "proxied": true
            }')

          echo "Response: $RESPONSE"

          SUCCESS=$(echo "$RESPONSE" | jq -r '.success')

          if [ "$SUCCESS" != "true" ]; then
            echo "Failed to add DNS record"
            echo "$RESPONSE" | jq '.errors'
            exit 1
          else
            echo "DNS record added successfully."
          fi