name: Setup SSL Certificate

on:
  workflow_call:
    secrets:
      SSH_REMOTE_HOST:
        required: true
      SSH_REMOTE_USER:
        required: true
      SSH_PRIVATE_KEY:
        required: true
      DOMAIN_NAME:
        required: true
      PROXY_PASS:
        required: true
      PROXY_PASS_PORT:
        required: true
    inputs:
      EMAIL_SSL:
        description: 'Email for SSL certificate registration'
        required: false
        type: string

jobs:
  setup-ssl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get GitHub Email
        id: get_email
        run: |
          EMAIL=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/user | jq -r '.email')
          echo "EMAIL=$EMAIL" >> $GITHUB_ENV

      - name: Install Certbot if not installed
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_REMOTE_HOST }}
          username: ${{ secrets.SSH_REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if ! command -v certbot &> /dev/null; then
              echo "Certbot not found. Installing..."
              sudo apt update
              sudo apt install -y software-properties-common
              sudo add-apt-repository -y ppa:certbot/certbot
              sudo apt update
              sudo apt install -y certbot python3-certbot-nginx
            else
              echo "Certbot is already installed."
            fi

      - name: SSL Configuration
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_REMOTE_HOST }}
          username: ${{ secrets.SSH_REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Obtain or renew SSL certificate
            sudo certbot certonly --nginx -d ${{ secrets.DOMAIN_NAME }} --email ${{ inputs.EMAIL_SSL || secrets.EMAIL_SSL }} --agree-tos --non-interactive || true

            # Renew all certificates if they are due
            sudo certbot renew --quiet --deploy-hook "sudo systemctl reload nginx"